=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaCloudClient::AssortmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssortmentsApi' do
  before do
    # run before each test
    @api_instance = KoronaCloudClient::AssortmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssortmentsApi' do
    it 'should create an instance of AssortmentsApi' do
      expect(@api_instance).to be_instance_of(KoronaCloudClient::AssortmentsApi)
    end
  end

  # unit tests for add_assortments
  # adds a batch of new assortments
  # @param korona_account_id account id of the KORONA Studio account
  # @param assortment array of new assortments
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :upsert when set to true, updates the object instead of generating a already-exists-error; deprecated, use writeMode ADD_OR_UPDATE instead
  # @option opts [String] :write_mode DEFAULT &#x3D; insert; ADD_OR_UPDATE &#x3D; insert or update, overwrite all non-null fields; ADD_OR_REPLACE &#x3D; insert or update, overwrite all fields
  # @return [Array<AddOrUpdateResult>]
  describe 'add_assortments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_assortment
  # deletes the single assortment
  # @param korona_account_id account id of the KORONA Studio account
  # @param assortment_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_assortment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_assortments
  # deletes a batch of assortments
  # @param korona_account_id account id of the KORONA Studio account
  # @param assortment array of existing assortments (id or number required)
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'delete_assortments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_assortment
  # returns the single assortment
  # @param korona_account_id account id of the KORONA Studio account
  # @param assortment_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [Assortment]
  describe 'get_assortment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_assortments
  # lists all assortments
  # @param korona_account_id account id of the KORONA Studio account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page number of the page to fetch
  # @option opts [Integer] :size amount of objects to return per page
  # @option opts [String] :sort attribute to sort by (multiple separated by comma; max. 5)
  # @option opts [Integer] :revision last revision number, objects with a greater revision than this will be returned
  # @option opts [Boolean] :include_deleted indicates deleted objects should be loaded or not (default: false)
  # @option opts [String] :number number of the related object
  # @return [ResultListAssortment]
  describe 'get_assortments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_assortment
  # updates the single assortment
  # @param korona_account_id account id of the KORONA Studio account
  # @param assortment_id id of the related object (important: id should match the uuid-format)
  # @param assortment the properties to update of the assortment
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_assortment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_assortments
  # updates a batch of assortments
  # @param korona_account_id account id of the KORONA Studio account
  # @param assortment array of existing assortments (id or number required)
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'update_assortments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
