=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaCloudClient::DataExchangeConfigurationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DataExchangeConfigurationsApi' do
  before do
    # run before each test
    @api_instance = KoronaCloudClient::DataExchangeConfigurationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DataExchangeConfigurationsApi' do
    it 'should create an instance of DataExchangeConfigurationsApi' do
      expect(@api_instance).to be_instance_of(KoronaCloudClient::DataExchangeConfigurationsApi)
    end
  end

  # unit tests for get_data_exchange_configuration
  # returns the single data exchange configuration
  # @param korona_account_id account id of the KORONA Studio account
  # @param data_exchange_configuration_type data exchange configuration type
  # @param [Hash] opts the optional parameters
  # @return [DataExchangeConfiguration]
  describe 'get_data_exchange_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_data_exchange_configurations
  # lists all data exchange configurations
  # @param korona_account_id account id of the KORONA Studio account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page number of the page to fetch
  # @option opts [Integer] :size amount of objects to return per page
  # @option opts [String] :sort attribute to sort by (multiple separated by comma; max. 5)
  # @option opts [Integer] :revision last revision number, objects with a greater revision than this will be returned
  # @option opts [Boolean] :include_deleted indicates deleted objects should be loaded or not (default: false)
  # @return [ResultListDataExchangeConfiguration]
  describe 'get_data_exchange_configurations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
