=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaCloudClient::ExternalFormApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExternalFormApi' do
  before do
    # run before each test
    @api_instance = KoronaCloudClient::ExternalFormApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalFormApi' do
    it 'should create an instance of ExternalFormApi' do
      expect(@api_instance).to be_instance_of(KoronaCloudClient::ExternalFormApi)
    end
  end

  # unit tests for add_external_forms
  # adds a batch of new external forms
  # @param korona_account_id account id of the KORONA Studio account
  # @param external_form array of new external forms
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :upsert when set to true, updates the object instead of generating a already-exists-error; deprecated, use writeMode ADD_OR_UPDATE instead
  # @option opts [String] :write_mode DEFAULT &#x3D; insert; ADD_OR_UPDATE &#x3D; insert or update, overwrite all non-null fields; ADD_OR_REPLACE &#x3D; insert or update, overwrite all fields
  # @return [Array<AddOrUpdateResult>]
  describe 'add_external_forms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_external_form
  # deletes a single external form
  # @param korona_account_id account id of the KORONA Studio account
  # @param external_form_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_external_form test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_external_forms
  # deletes a batch of external forms
  # @param korona_account_id account id of the KORONA Studio account
  # @param [Hash] opts the optional parameters
  # @option opts [Array<ExternalForm>] :external_form array of existing external forms (id or number required)
  # @return [Array<AddOrUpdateResult>]
  describe 'delete_external_forms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_external_form
  # returns a single external form
  # @param korona_account_id account id of the KORONA Studio account
  # @param external_form_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [ExternalForm]
  describe 'get_external_form test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_external_forms
  # lists all external forms
  # @param korona_account_id account id of the KORONA Studio account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page number of the page to fetch
  # @option opts [Integer] :size amount of objects to return per page
  # @option opts [String] :sort attribute to sort by (multiple separated by comma; max. 5)
  # @option opts [Integer] :revision last revision number, objects with a greater revision than this will be returned
  # @option opts [Boolean] :include_deleted indicates deleted objects should be loaded or not (default: false)
  # @option opts [String] :number number of the related object
  # @return [ResultListExternalForm]
  describe 'get_external_forms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_external_form
  # updates the single external form
  # @param korona_account_id account id of the KORONA Studio account
  # @param external_form_id id of the related object (important: id should match the uuid-format)
  # @param external_form the properties to update of the external form
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_external_form test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_external_forms
  # updates a batch of external forms
  # @param korona_account_id account id of the KORONA Studio account
  # @param external_form array of existing external forms (id or number required)
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'update_external_forms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
