=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaCloudClient::LoyaltyCardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoyaltyCardsApi' do
  before do
    # run before each test
    @api_instance = KoronaCloudClient::LoyaltyCardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoyaltyCardsApi' do
    it 'should create an instance of LoyaltyCardsApi' do
      expect(@api_instance).to be_instance_of(KoronaCloudClient::LoyaltyCardsApi)
    end
  end

  # unit tests for add_loyalty_cards
  # adds a batch of new loyalty cards
  # @param korona_account_id account id of the KORONA Studio account
  # @param loyalty_card array of new loyalty cards
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :upsert when set to true, updates the object instead of generating a already-exists-error; deprecated, use writeMode ADD_OR_UPDATE instead
  # @option opts [String] :write_mode DEFAULT &#x3D; insert; ADD_OR_UPDATE &#x3D; insert or update, overwrite all non-null fields; ADD_OR_REPLACE &#x3D; insert or update, overwrite all fields
  # @return [Array<AddOrUpdateResult>]
  describe 'add_loyalty_cards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_loyalty_card
  # deletes the single loyalty card
  # @param korona_account_id account id of the KORONA Studio account
  # @param loyalty_card_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_loyalty_card test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_loyalty_cards
  # deletes a batch of loyalty cards
  # @param korona_account_id account id of the KORONA Studio account
  # @param loyalty_card array of existing loyalty cards (id, number or customerId required)
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'delete_loyalty_cards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loyalty_card
  # returns the single loyalty card
  # @param korona_account_id account id of the KORONA Studio account
  # @param loyalty_card_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [LoyaltyCard]
  describe 'get_loyalty_card test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loyalty_cards
  # lists all loyalty cards
  # @param korona_account_id account id of the KORONA Studio account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page number of the page to fetch
  # @option opts [Integer] :size amount of objects to return per page
  # @option opts [String] :sort attribute to sort by (multiple separated by comma; max. 5)
  # @option opts [Integer] :revision last revision number, objects with a greater revision than this will be returned
  # @option opts [String] :number number of the related object
  # @option opts [Boolean] :include_deleted indicates deleted objects should be loaded or not (default: false)
  # @option opts [String] :customer customer id to filter by
  # @return [ResultListLoyaltyCard]
  describe 'get_loyalty_cards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_loyalty_card
  # updates the single loyalty card; if [number] is set, the number of the object will change and the resource location as well
  # @param korona_account_id account id of the KORONA Studio account
  # @param loyalty_card_id id of the related object (important: id should match the uuid-format)
  # @param loyalty_card the object to update
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_loyalty_card test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_loyalty_cards
  # updates a batch of loyalty cards; [number] must be set in the objects, otherwise the object cannot be updated
  # @param korona_account_id account id of the KORONA Studio account
  # @param loyalty_card an array of existing loyalty cards
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'update_loyalty_cards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
