=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaCloudClient::PosPageLayoutConfigurationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PosPageLayoutConfigurationsApi' do
  before do
    # run before each test
    @api_instance = KoronaCloudClient::PosPageLayoutConfigurationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PosPageLayoutConfigurationsApi' do
    it 'should create an instance of PosPageLayoutConfigurationsApi' do
      expect(@api_instance).to be_instance_of(KoronaCloudClient::PosPageLayoutConfigurationsApi)
    end
  end

  # unit tests for add_pos_page_layout_configurations
  # adds a batch of new pos page layout configurations
  # @param korona_account_id account id of the KORONA Studio account
  # @param pos_page_layout_configuration array of new pos page layout configurations
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :upsert when set to true, updates the object instead of generating a already-exists-error; deprecated, use writeMode ADD_OR_UPDATE instead
  # @option opts [String] :write_mode DEFAULT &#x3D; insert; ADD_OR_UPDATE &#x3D; insert or update, overwrite all non-null fields; ADD_OR_REPLACE &#x3D; insert or update, overwrite all fields
  # @return [Array<AddOrUpdateResult>]
  describe 'add_pos_page_layout_configurations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_pos_page_layout_configuration
  # deletes the single pos page layout configuration
  # @param korona_account_id account id of the KORONA Studio account
  # @param pos_page_layout_configuration_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_pos_page_layout_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_pos_page_layout_configurations
  # deletes a batch of pos page layout configurations
  # @param korona_account_id account id of the KORONA Studio account
  # @param pos_page_layout_configuration array of existing pos page layout configurations (id or number required)
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'delete_pos_page_layout_configurations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pos_page_layout_configuration
  # returns the single pos page layout configuration
  # @param korona_account_id account id of the KORONA Studio account
  # @param pos_page_layout_configuration_id id of the related object (important: id should match the uuid-format)
  # @param [Hash] opts the optional parameters
  # @return [PosPageLayoutConfiguration]
  describe 'get_pos_page_layout_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pos_page_layout_configurations
  # lists all pos page layout configurations
  # @param korona_account_id account id of the KORONA Studio account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page number of the page to fetch
  # @option opts [Integer] :size amount of objects to return per page
  # @option opts [String] :sort attribute to sort by (multiple separated by comma; max. 5)
  # @option opts [Integer] :revision last revision number, objects with a greater revision than this will be returned
  # @option opts [Boolean] :include_deleted indicates deleted objects should be loaded or not (default: false)
  # @option opts [String] :number number of the related object
  # @return [ResultListPosPageLayoutConfiguration]
  describe 'get_pos_page_layout_configurations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_pos_page_layout_configuration
  # updates the single pos page layout configuration; if [number] is set, the number of the object will change and the resource location as well
  # @param korona_account_id account id of the KORONA Studio account
  # @param pos_page_layout_configuration_id id of the related object (important: id should match the uuid-format)
  # @param pos_page_layout_configuration the properties to update of the pos page layout configuration
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_pos_page_layout_configuration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_pos_page_layout_configurations
  # updates a batch of pos page layout configurations; [number] must be set in the objects, otherwise the object cannot be updated
  # @param korona_account_id account id of the KORONA Studio account
  # @param pos_page_layout_configuration an array of existing pos page layout configurations
  # @param [Hash] opts the optional parameters
  # @return [Array<AddOrUpdateResult>]
  describe 'update_pos_page_layout_configurations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
