=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::FiscalUnitStateVersionInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::FiscalUnitStateVersionInfo do
  let(:instance) { KoronaCloudClient::FiscalUnitStateVersionInfo.new }

  describe 'test an instance of FiscalUnitStateVersionInfo' do
    it 'should create an instance of FiscalUnitStateVersionInfo' do
      expect(instance).to be_instance_of(KoronaCloudClient::FiscalUnitStateVersionInfo)
    end
  end
  describe 'test attribute "api"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "hardware"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "software"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
