=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::ForbiddenErrorModel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::ForbiddenErrorModel do
  #let(:instance) { KoronaCloudClient::ForbiddenErrorModel.new }

  describe 'test an instance of ForbiddenErrorModel' do
    it 'should create an instance of ForbiddenErrorModel' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::ForbiddenErrorModel)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CLOUD_ACCOUNT_DISABLED", "POINT_OF_SALE_NOT_EXTERNAL", "POINT_OF_SALE_NOT_COUPLED", "POINT_OF_SALE_COUPLED_WITH_OTHER_DEVICE", "DELETE_NOT_ALLOWED", "SAVE_OR_UPDATE_NOT_ALLOWED", "ADDITIONAL_CLOUD_PACKAGE_REQUIRED", "ADDITIONAL_API_ACCESS_REQUIRED", "API_USAGE_DISABLED", "API_USER_NOT_MATCHING_POS"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

end
