=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::OpeningHours
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::OpeningHours do
  #let(:instance) { KoronaCloudClient::OpeningHours.new }

  describe 'test an instance of OpeningHours' do
    it 'should create an instance of OpeningHours' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::OpeningHours)
    end
  end

  describe 'test attribute "week_day"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"])
      # validator.allowable_values.each do |value|
      #   expect { instance.week_day = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
