=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PaymentTerminalReceipt
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PaymentTerminalReceipt do
  #let(:instance) { KoronaCloudClient::PaymentTerminalReceipt.new }

  describe 'test an instance of PaymentTerminalReceipt' do
    it 'should create an instance of PaymentTerminalReceipt' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::PaymentTerminalReceipt)
    end
  end

  describe 'test attribute "terminal_receipt_print_lines"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "terminal_receipt_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["OTHER", "MERCHANT_RECEIPT", "CARDHOLDER_RECEIPT"])
      # validator.allowable_values.each do |value|
      #   expect { instance.terminal_receipt_type = value }.not_to raise_error
      # end
    end
  end

end
