=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PeriodRevenueDataMapStringRevenueData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PeriodRevenueDataMapStringRevenueData do
  #let(:instance) { KoronaCloudClient::PeriodRevenueDataMapStringRevenueData.new }

  describe 'test an instance of PeriodRevenueDataMapStringRevenueData' do
    it 'should create an instance of PeriodRevenueDataMapStringRevenueData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::PeriodRevenueDataMapStringRevenueData)
    end
  end

  describe 'test attribute "start"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_end"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
