=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PosButtonLayout
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PosButtonLayout do
  #let(:instance) { KoronaCloudClient::PosButtonLayout.new }

  describe 'test an instance of PosButtonLayout' do
    it 'should create an instance of PosButtonLayout' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::PosButtonLayout)
    end
  end

  describe 'test attribute "active"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "revision"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "buttons"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SMALL", "BIG", "WIDE", "LAYOUT_1X10", "LAYOUT_1X8", "LAYOUT_1X6", "LAYOUT_2X12", "LAYOUT_2X10", "LAYOUT_2X8", "LAYOUT_2X6", "LAYOUT_3X10", "LAYOUT_3X8", "LAYOUT_3X6", "LAYOUT_4X8", "LAYOUT_4X6", "LAYOUT_4X4", "LAYOUT_4X2"])
      # validator.allowable_values.each do |value|
      #   expect { instance.size = value }.not_to raise_error
      # end
    end
  end

end
