=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::PromotionBenefitExtendedDiscountDiscountCalculation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::PromotionBenefitExtendedDiscountDiscountCalculation do
  #let(:instance) { KoronaCloudClient::PromotionBenefitExtendedDiscountDiscountCalculation.new }

  describe 'test an instance of PromotionBenefitExtendedDiscountDiscountCalculation' do
    it 'should create an instance of PromotionBenefitExtendedDiscountDiscountCalculation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::PromotionBenefitExtendedDiscountDiscountCalculation)
    end
  end

  describe 'test attribute "operand"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "operator"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["EQUALS", "MINUS", "PERCENTAGE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.operator = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "position_selection_criteria"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["RECEIPT", "REMAINDER", "SELECTION", "SUB_SELECTION"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reference = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "sum_reference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["RECEIPT", "REMAINDER", "SELECTION", "SUB_SELECTION"])
      # validator.allowable_values.each do |value|
      #   expect { instance.sum_reference = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "receipt_discount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
