=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::Service
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::Service do
  #let(:instance) { KoronaCloudClient::Service.new }

  describe 'test an instance of Service' do
    it 'should create an instance of Service' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::Service)
    end
  end

  describe 'test attribute "parameter"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CASH", "MERCHANTWARE", "MERCURY", "KORONA_PREPAID", "CREDIT_AUTHORIZATION_TERMINAL"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "processing_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DEFAULT_PAYMENT_PROCESSING", "PRE_AUTH", "GENIUS", "WEB_KEYED", "WEB_SWIPED", "NONE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.processing_mode = value }.not_to raise_error
      # end
    end
  end

end
