=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::StockReceiptItemAmount
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::StockReceiptItemAmount do
  #let(:instance) { KoronaCloudClient::StockReceiptItemAmount.new }

  describe 'test an instance of StockReceiptItemAmount' do
    it 'should create an instance of StockReceiptItemAmount' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::StockReceiptItemAmount)
    end
  end

  describe 'test attribute "expected"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "received"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
