=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::VoucherConfigurationFollowUpProducts
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::VoucherConfigurationFollowUpProducts do
  #let(:instance) { KoronaCloudClient::VoucherConfigurationFollowUpProducts.new }

  describe 'test an instance of VoucherConfigurationFollowUpProducts' do
    it 'should create an instance of VoucherConfigurationFollowUpProducts' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::VoucherConfigurationFollowUpProducts)
    end
  end

  describe 'test attribute "price_transfer"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "product"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "tag"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
