=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KoronaCloudClient::Weather
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KoronaCloudClient::Weather do
  #let(:instance) { KoronaCloudClient::Weather.new }

  describe 'test an instance of Weather' do
    it 'should create an instance of Weather' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KoronaCloudClient::Weather)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "temperature"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "temperature_unit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CELSIUS", "FAHRENHEIT", "KELVIN"])
      # validator.allowable_values.each do |value|
      #   expect { instance.temperature_unit = value }.not_to raise_error
      # end
    end
  end

end
