=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module KoronaCloudClient
  class AccountMaxRevisions
    attr_accessor :account

    attr_accessor :additional_receipt_info_type

    attr_accessor :assortment

    attr_accessor :attendance

    attr_accessor :cashier

    attr_accessor :cashier_role

    attr_accessor :cashier_verification_requirement

    attr_accessor :commodity_group

    attr_accessor :contra_account

    attr_accessor :cost_center

    attr_accessor :coupon

    attr_accessor :currency

    attr_accessor :customer

    attr_accessor :customer_display_configuration

    attr_accessor :customer_group

    attr_accessor :customer_order

    attr_accessor :data_exchange_configuration

    attr_accessor :delivery_note

    attr_accessor :device_configuration_variable

    attr_accessor :discount_configuration

    attr_accessor :discount_level

    attr_accessor :dispatch_notification

    attr_accessor :dispatch_notification_item

    attr_accessor :economic_zone

    attr_accessor :end_of_day_statement

    attr_accessor :entry_gate

    attr_accessor :event

    attr_accessor :external_system_call

    attr_accessor :fiscal_unit

    attr_accessor :image

    attr_accessor :info_text

    attr_accessor :inventory

    attr_accessor :inventory_list

    attr_accessor :inventory_list_item

    attr_accessor :item_sequence

    attr_accessor :language

    attr_accessor :loyalty_card

    attr_accessor :number_range_configuration

    attr_accessor :order_portal_supplier

    attr_accessor :organizational_unit

    attr_accessor :payment_method

    attr_accessor :payment_method_category

    attr_accessor :pos

    attr_accessor :pos_balance

    attr_accessor :pos_button_layout

    attr_accessor :pos_page_layout_configuration

    attr_accessor :pos_profile

    attr_accessor :price

    attr_accessor :price_group

    attr_accessor :price_rule

    attr_accessor :product

    attr_accessor :production_type

    attr_accessor :promotion

    attr_accessor :receipt

    attr_accessor :receipt_layout_configuration

    attr_accessor :report_file

    attr_accessor :revenue_account

    attr_accessor :sales_tax

    attr_accessor :sector

    attr_accessor :special_price_configuration

    attr_accessor :stock_adjustment

    attr_accessor :stock_adjustment_item

    attr_accessor :stock_order

    attr_accessor :stock_order_item

    attr_accessor :stock_receipt

    attr_accessor :stock_receipt_item

    attr_accessor :supplier

    attr_accessor :tag

    attr_accessor :ticket_definition

    attr_accessor :time_tracking_entity

    attr_accessor :time_tracking_entry

    attr_accessor :user

    attr_accessor :user_role

    attr_accessor :voucher

    attr_accessor :voucher_configuration

    attr_accessor :voucher_transaction

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account' => :'account',
        :'additional_receipt_info_type' => :'additionalReceiptInfoType',
        :'assortment' => :'assortment',
        :'attendance' => :'attendance',
        :'cashier' => :'cashier',
        :'cashier_role' => :'cashierRole',
        :'cashier_verification_requirement' => :'cashierVerificationRequirement',
        :'commodity_group' => :'commodityGroup',
        :'contra_account' => :'contraAccount',
        :'cost_center' => :'costCenter',
        :'coupon' => :'coupon',
        :'currency' => :'currency',
        :'customer' => :'customer',
        :'customer_display_configuration' => :'customerDisplayConfiguration',
        :'customer_group' => :'customerGroup',
        :'customer_order' => :'customerOrder',
        :'data_exchange_configuration' => :'dataExchangeConfiguration',
        :'delivery_note' => :'deliveryNote',
        :'device_configuration_variable' => :'deviceConfigurationVariable',
        :'discount_configuration' => :'discountConfiguration',
        :'discount_level' => :'discountLevel',
        :'dispatch_notification' => :'dispatchNotification',
        :'dispatch_notification_item' => :'dispatchNotificationItem',
        :'economic_zone' => :'economicZone',
        :'end_of_day_statement' => :'endOfDayStatement',
        :'entry_gate' => :'entryGate',
        :'event' => :'event',
        :'external_system_call' => :'externalSystemCall',
        :'fiscal_unit' => :'fiscalUnit',
        :'image' => :'image',
        :'info_text' => :'infoText',
        :'inventory' => :'inventory',
        :'inventory_list' => :'inventoryList',
        :'inventory_list_item' => :'inventoryListItem',
        :'item_sequence' => :'itemSequence',
        :'language' => :'language',
        :'loyalty_card' => :'loyaltyCard',
        :'number_range_configuration' => :'numberRangeConfiguration',
        :'order_portal_supplier' => :'orderPortalSupplier',
        :'organizational_unit' => :'organizationalUnit',
        :'payment_method' => :'paymentMethod',
        :'payment_method_category' => :'paymentMethodCategory',
        :'pos' => :'pos',
        :'pos_balance' => :'posBalance',
        :'pos_button_layout' => :'posButtonLayout',
        :'pos_page_layout_configuration' => :'posPageLayoutConfiguration',
        :'pos_profile' => :'posProfile',
        :'price' => :'price',
        :'price_group' => :'priceGroup',
        :'price_rule' => :'priceRule',
        :'product' => :'product',
        :'production_type' => :'productionType',
        :'promotion' => :'promotion',
        :'receipt' => :'receipt',
        :'receipt_layout_configuration' => :'receiptLayoutConfiguration',
        :'report_file' => :'reportFile',
        :'revenue_account' => :'revenueAccount',
        :'sales_tax' => :'salesTax',
        :'sector' => :'sector',
        :'special_price_configuration' => :'specialPriceConfiguration',
        :'stock_adjustment' => :'stockAdjustment',
        :'stock_adjustment_item' => :'stockAdjustmentItem',
        :'stock_order' => :'stockOrder',
        :'stock_order_item' => :'stockOrderItem',
        :'stock_receipt' => :'stockReceipt',
        :'stock_receipt_item' => :'stockReceiptItem',
        :'supplier' => :'supplier',
        :'tag' => :'tag',
        :'ticket_definition' => :'ticketDefinition',
        :'time_tracking_entity' => :'timeTrackingEntity',
        :'time_tracking_entry' => :'timeTrackingEntry',
        :'user' => :'user',
        :'user_role' => :'userRole',
        :'voucher' => :'voucher',
        :'voucher_configuration' => :'voucherConfiguration',
        :'voucher_transaction' => :'voucherTransaction'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account' => :'Integer',
        :'additional_receipt_info_type' => :'Integer',
        :'assortment' => :'Integer',
        :'attendance' => :'Integer',
        :'cashier' => :'Integer',
        :'cashier_role' => :'Integer',
        :'cashier_verification_requirement' => :'Integer',
        :'commodity_group' => :'Integer',
        :'contra_account' => :'Integer',
        :'cost_center' => :'Integer',
        :'coupon' => :'Integer',
        :'currency' => :'Integer',
        :'customer' => :'Integer',
        :'customer_display_configuration' => :'Integer',
        :'customer_group' => :'Integer',
        :'customer_order' => :'Integer',
        :'data_exchange_configuration' => :'Integer',
        :'delivery_note' => :'Integer',
        :'device_configuration_variable' => :'Integer',
        :'discount_configuration' => :'Integer',
        :'discount_level' => :'Integer',
        :'dispatch_notification' => :'Integer',
        :'dispatch_notification_item' => :'Integer',
        :'economic_zone' => :'Integer',
        :'end_of_day_statement' => :'Integer',
        :'entry_gate' => :'Integer',
        :'event' => :'Integer',
        :'external_system_call' => :'Integer',
        :'fiscal_unit' => :'Integer',
        :'image' => :'Integer',
        :'info_text' => :'Integer',
        :'inventory' => :'Integer',
        :'inventory_list' => :'Integer',
        :'inventory_list_item' => :'Integer',
        :'item_sequence' => :'Integer',
        :'language' => :'Integer',
        :'loyalty_card' => :'Integer',
        :'number_range_configuration' => :'Integer',
        :'order_portal_supplier' => :'Integer',
        :'organizational_unit' => :'Integer',
        :'payment_method' => :'Integer',
        :'payment_method_category' => :'Integer',
        :'pos' => :'Integer',
        :'pos_balance' => :'Integer',
        :'pos_button_layout' => :'Integer',
        :'pos_page_layout_configuration' => :'Integer',
        :'pos_profile' => :'Integer',
        :'price' => :'Integer',
        :'price_group' => :'Integer',
        :'price_rule' => :'Integer',
        :'product' => :'Integer',
        :'production_type' => :'Integer',
        :'promotion' => :'Integer',
        :'receipt' => :'Integer',
        :'receipt_layout_configuration' => :'Integer',
        :'report_file' => :'Integer',
        :'revenue_account' => :'Integer',
        :'sales_tax' => :'Integer',
        :'sector' => :'Integer',
        :'special_price_configuration' => :'Integer',
        :'stock_adjustment' => :'Integer',
        :'stock_adjustment_item' => :'Integer',
        :'stock_order' => :'Integer',
        :'stock_order_item' => :'Integer',
        :'stock_receipt' => :'Integer',
        :'stock_receipt_item' => :'Integer',
        :'supplier' => :'Integer',
        :'tag' => :'Integer',
        :'ticket_definition' => :'Integer',
        :'time_tracking_entity' => :'Integer',
        :'time_tracking_entry' => :'Integer',
        :'user' => :'Integer',
        :'user_role' => :'Integer',
        :'voucher' => :'Integer',
        :'voucher_configuration' => :'Integer',
        :'voucher_transaction' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::AccountMaxRevisions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::AccountMaxRevisions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account')
        self.account = attributes[:'account']
      end

      if attributes.key?(:'additional_receipt_info_type')
        self.additional_receipt_info_type = attributes[:'additional_receipt_info_type']
      end

      if attributes.key?(:'assortment')
        self.assortment = attributes[:'assortment']
      end

      if attributes.key?(:'attendance')
        self.attendance = attributes[:'attendance']
      end

      if attributes.key?(:'cashier')
        self.cashier = attributes[:'cashier']
      end

      if attributes.key?(:'cashier_role')
        self.cashier_role = attributes[:'cashier_role']
      end

      if attributes.key?(:'cashier_verification_requirement')
        self.cashier_verification_requirement = attributes[:'cashier_verification_requirement']
      end

      if attributes.key?(:'commodity_group')
        self.commodity_group = attributes[:'commodity_group']
      end

      if attributes.key?(:'contra_account')
        self.contra_account = attributes[:'contra_account']
      end

      if attributes.key?(:'cost_center')
        self.cost_center = attributes[:'cost_center']
      end

      if attributes.key?(:'coupon')
        self.coupon = attributes[:'coupon']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      end

      if attributes.key?(:'customer_display_configuration')
        self.customer_display_configuration = attributes[:'customer_display_configuration']
      end

      if attributes.key?(:'customer_group')
        self.customer_group = attributes[:'customer_group']
      end

      if attributes.key?(:'customer_order')
        self.customer_order = attributes[:'customer_order']
      end

      if attributes.key?(:'data_exchange_configuration')
        self.data_exchange_configuration = attributes[:'data_exchange_configuration']
      end

      if attributes.key?(:'delivery_note')
        self.delivery_note = attributes[:'delivery_note']
      end

      if attributes.key?(:'device_configuration_variable')
        self.device_configuration_variable = attributes[:'device_configuration_variable']
      end

      if attributes.key?(:'discount_configuration')
        self.discount_configuration = attributes[:'discount_configuration']
      end

      if attributes.key?(:'discount_level')
        self.discount_level = attributes[:'discount_level']
      end

      if attributes.key?(:'dispatch_notification')
        self.dispatch_notification = attributes[:'dispatch_notification']
      end

      if attributes.key?(:'dispatch_notification_item')
        self.dispatch_notification_item = attributes[:'dispatch_notification_item']
      end

      if attributes.key?(:'economic_zone')
        self.economic_zone = attributes[:'economic_zone']
      end

      if attributes.key?(:'end_of_day_statement')
        self.end_of_day_statement = attributes[:'end_of_day_statement']
      end

      if attributes.key?(:'entry_gate')
        self.entry_gate = attributes[:'entry_gate']
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      end

      if attributes.key?(:'external_system_call')
        self.external_system_call = attributes[:'external_system_call']
      end

      if attributes.key?(:'fiscal_unit')
        self.fiscal_unit = attributes[:'fiscal_unit']
      end

      if attributes.key?(:'image')
        self.image = attributes[:'image']
      end

      if attributes.key?(:'info_text')
        self.info_text = attributes[:'info_text']
      end

      if attributes.key?(:'inventory')
        self.inventory = attributes[:'inventory']
      end

      if attributes.key?(:'inventory_list')
        self.inventory_list = attributes[:'inventory_list']
      end

      if attributes.key?(:'inventory_list_item')
        self.inventory_list_item = attributes[:'inventory_list_item']
      end

      if attributes.key?(:'item_sequence')
        self.item_sequence = attributes[:'item_sequence']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'loyalty_card')
        self.loyalty_card = attributes[:'loyalty_card']
      end

      if attributes.key?(:'number_range_configuration')
        self.number_range_configuration = attributes[:'number_range_configuration']
      end

      if attributes.key?(:'order_portal_supplier')
        self.order_portal_supplier = attributes[:'order_portal_supplier']
      end

      if attributes.key?(:'organizational_unit')
        self.organizational_unit = attributes[:'organizational_unit']
      end

      if attributes.key?(:'payment_method')
        self.payment_method = attributes[:'payment_method']
      end

      if attributes.key?(:'payment_method_category')
        self.payment_method_category = attributes[:'payment_method_category']
      end

      if attributes.key?(:'pos')
        self.pos = attributes[:'pos']
      end

      if attributes.key?(:'pos_balance')
        self.pos_balance = attributes[:'pos_balance']
      end

      if attributes.key?(:'pos_button_layout')
        self.pos_button_layout = attributes[:'pos_button_layout']
      end

      if attributes.key?(:'pos_page_layout_configuration')
        self.pos_page_layout_configuration = attributes[:'pos_page_layout_configuration']
      end

      if attributes.key?(:'pos_profile')
        self.pos_profile = attributes[:'pos_profile']
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      end

      if attributes.key?(:'price_group')
        self.price_group = attributes[:'price_group']
      end

      if attributes.key?(:'price_rule')
        self.price_rule = attributes[:'price_rule']
      end

      if attributes.key?(:'product')
        self.product = attributes[:'product']
      end

      if attributes.key?(:'production_type')
        self.production_type = attributes[:'production_type']
      end

      if attributes.key?(:'promotion')
        self.promotion = attributes[:'promotion']
      end

      if attributes.key?(:'receipt')
        self.receipt = attributes[:'receipt']
      end

      if attributes.key?(:'receipt_layout_configuration')
        self.receipt_layout_configuration = attributes[:'receipt_layout_configuration']
      end

      if attributes.key?(:'report_file')
        self.report_file = attributes[:'report_file']
      end

      if attributes.key?(:'revenue_account')
        self.revenue_account = attributes[:'revenue_account']
      end

      if attributes.key?(:'sales_tax')
        self.sales_tax = attributes[:'sales_tax']
      end

      if attributes.key?(:'sector')
        self.sector = attributes[:'sector']
      end

      if attributes.key?(:'special_price_configuration')
        self.special_price_configuration = attributes[:'special_price_configuration']
      end

      if attributes.key?(:'stock_adjustment')
        self.stock_adjustment = attributes[:'stock_adjustment']
      end

      if attributes.key?(:'stock_adjustment_item')
        self.stock_adjustment_item = attributes[:'stock_adjustment_item']
      end

      if attributes.key?(:'stock_order')
        self.stock_order = attributes[:'stock_order']
      end

      if attributes.key?(:'stock_order_item')
        self.stock_order_item = attributes[:'stock_order_item']
      end

      if attributes.key?(:'stock_receipt')
        self.stock_receipt = attributes[:'stock_receipt']
      end

      if attributes.key?(:'stock_receipt_item')
        self.stock_receipt_item = attributes[:'stock_receipt_item']
      end

      if attributes.key?(:'supplier')
        self.supplier = attributes[:'supplier']
      end

      if attributes.key?(:'tag')
        self.tag = attributes[:'tag']
      end

      if attributes.key?(:'ticket_definition')
        self.ticket_definition = attributes[:'ticket_definition']
      end

      if attributes.key?(:'time_tracking_entity')
        self.time_tracking_entity = attributes[:'time_tracking_entity']
      end

      if attributes.key?(:'time_tracking_entry')
        self.time_tracking_entry = attributes[:'time_tracking_entry']
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'user_role')
        self.user_role = attributes[:'user_role']
      end

      if attributes.key?(:'voucher')
        self.voucher = attributes[:'voucher']
      end

      if attributes.key?(:'voucher_configuration')
        self.voucher_configuration = attributes[:'voucher_configuration']
      end

      if attributes.key?(:'voucher_transaction')
        self.voucher_transaction = attributes[:'voucher_transaction']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account == o.account &&
          additional_receipt_info_type == o.additional_receipt_info_type &&
          assortment == o.assortment &&
          attendance == o.attendance &&
          cashier == o.cashier &&
          cashier_role == o.cashier_role &&
          cashier_verification_requirement == o.cashier_verification_requirement &&
          commodity_group == o.commodity_group &&
          contra_account == o.contra_account &&
          cost_center == o.cost_center &&
          coupon == o.coupon &&
          currency == o.currency &&
          customer == o.customer &&
          customer_display_configuration == o.customer_display_configuration &&
          customer_group == o.customer_group &&
          customer_order == o.customer_order &&
          data_exchange_configuration == o.data_exchange_configuration &&
          delivery_note == o.delivery_note &&
          device_configuration_variable == o.device_configuration_variable &&
          discount_configuration == o.discount_configuration &&
          discount_level == o.discount_level &&
          dispatch_notification == o.dispatch_notification &&
          dispatch_notification_item == o.dispatch_notification_item &&
          economic_zone == o.economic_zone &&
          end_of_day_statement == o.end_of_day_statement &&
          entry_gate == o.entry_gate &&
          event == o.event &&
          external_system_call == o.external_system_call &&
          fiscal_unit == o.fiscal_unit &&
          image == o.image &&
          info_text == o.info_text &&
          inventory == o.inventory &&
          inventory_list == o.inventory_list &&
          inventory_list_item == o.inventory_list_item &&
          item_sequence == o.item_sequence &&
          language == o.language &&
          loyalty_card == o.loyalty_card &&
          number_range_configuration == o.number_range_configuration &&
          order_portal_supplier == o.order_portal_supplier &&
          organizational_unit == o.organizational_unit &&
          payment_method == o.payment_method &&
          payment_method_category == o.payment_method_category &&
          pos == o.pos &&
          pos_balance == o.pos_balance &&
          pos_button_layout == o.pos_button_layout &&
          pos_page_layout_configuration == o.pos_page_layout_configuration &&
          pos_profile == o.pos_profile &&
          price == o.price &&
          price_group == o.price_group &&
          price_rule == o.price_rule &&
          product == o.product &&
          production_type == o.production_type &&
          promotion == o.promotion &&
          receipt == o.receipt &&
          receipt_layout_configuration == o.receipt_layout_configuration &&
          report_file == o.report_file &&
          revenue_account == o.revenue_account &&
          sales_tax == o.sales_tax &&
          sector == o.sector &&
          special_price_configuration == o.special_price_configuration &&
          stock_adjustment == o.stock_adjustment &&
          stock_adjustment_item == o.stock_adjustment_item &&
          stock_order == o.stock_order &&
          stock_order_item == o.stock_order_item &&
          stock_receipt == o.stock_receipt &&
          stock_receipt_item == o.stock_receipt_item &&
          supplier == o.supplier &&
          tag == o.tag &&
          ticket_definition == o.ticket_definition &&
          time_tracking_entity == o.time_tracking_entity &&
          time_tracking_entry == o.time_tracking_entry &&
          user == o.user &&
          user_role == o.user_role &&
          voucher == o.voucher &&
          voucher_configuration == o.voucher_configuration &&
          voucher_transaction == o.voucher_transaction
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account, additional_receipt_info_type, assortment, attendance, cashier, cashier_role, cashier_verification_requirement, commodity_group, contra_account, cost_center, coupon, currency, customer, customer_display_configuration, customer_group, customer_order, data_exchange_configuration, delivery_note, device_configuration_variable, discount_configuration, discount_level, dispatch_notification, dispatch_notification_item, economic_zone, end_of_day_statement, entry_gate, event, external_system_call, fiscal_unit, image, info_text, inventory, inventory_list, inventory_list_item, item_sequence, language, loyalty_card, number_range_configuration, order_portal_supplier, organizational_unit, payment_method, payment_method_category, pos, pos_balance, pos_button_layout, pos_page_layout_configuration, pos_profile, price, price_group, price_rule, product, production_type, promotion, receipt, receipt_layout_configuration, report_file, revenue_account, sales_tax, sector, special_price_configuration, stock_adjustment, stock_adjustment_item, stock_order, stock_order_item, stock_receipt, stock_receipt_item, supplier, tag, ticket_definition, time_tracking_entity, time_tracking_entry, user, user_role, voucher, voucher_configuration, voucher_transaction].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = KoronaCloudClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
