=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  class DsfinvkExport < ApiModelBase
    # global object uuid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
    attr_accessor :id

    attr_accessor :point_of_sale

    # yyyy-MM-dd'T'HH:mm:ssXXX
    attr_accessor :min_booking_time

    # yyyy-MM-dd'T'HH:mm:ssXXX
    attr_accessor :max_booking_time

    # Status of the export.
    attr_accessor :state

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'point_of_sale' => :'pointOfSale',
        :'min_booking_time' => :'minBookingTime',
        :'max_booking_time' => :'maxBookingTime',
        :'state' => :'state'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'point_of_sale' => :'ModelReference',
        :'min_booking_time' => :'Time',
        :'max_booking_time' => :'Time',
        :'state' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::DsfinvkExport` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::DsfinvkExport`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'point_of_sale')
        self.point_of_sale = attributes[:'point_of_sale']
      else
        self.point_of_sale = nil
      end

      if attributes.key?(:'min_booking_time')
        self.min_booking_time = attributes[:'min_booking_time']
      else
        self.min_booking_time = nil
      end

      if attributes.key?(:'max_booking_time')
        self.max_booking_time = attributes[:'max_booking_time']
      else
        self.max_booking_time = nil
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @point_of_sale.nil?
        invalid_properties.push('invalid value for "point_of_sale", point_of_sale cannot be nil.')
      end

      if @min_booking_time.nil?
        invalid_properties.push('invalid value for "min_booking_time", min_booking_time cannot be nil.')
      end

      if @max_booking_time.nil?
        invalid_properties.push('invalid value for "max_booking_time", max_booking_time cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @point_of_sale.nil?
      return false if @min_booking_time.nil?
      return false if @max_booking_time.nil?
      state_validator = EnumAttributeValidator.new('String', ["PENDING", "RUNNING", "FINISHED", "FAILED"])
      return false unless state_validator.valid?(@state)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] point_of_sale Value to be assigned
    def point_of_sale=(point_of_sale)
      if point_of_sale.nil?
        fail ArgumentError, 'point_of_sale cannot be nil'
      end

      @point_of_sale = point_of_sale
    end

    # Custom attribute writer method with validation
    # @param [Object] min_booking_time Value to be assigned
    def min_booking_time=(min_booking_time)
      if min_booking_time.nil?
        fail ArgumentError, 'min_booking_time cannot be nil'
      end

      @min_booking_time = min_booking_time
    end

    # Custom attribute writer method with validation
    # @param [Object] max_booking_time Value to be assigned
    def max_booking_time=(max_booking_time)
      if max_booking_time.nil?
        fail ArgumentError, 'max_booking_time cannot be nil'
      end

      @max_booking_time = max_booking_time
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ["PENDING", "RUNNING", "FINISHED", "FAILED"])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          point_of_sale == o.point_of_sale &&
          min_booking_time == o.min_booking_time &&
          max_booking_time == o.max_booking_time &&
          state == o.state
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, point_of_sale, min_booking_time, max_booking_time, state].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
