=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  # External system calls are used at the point of sale to interact with third party applications. Please review the POS client API documentation for more information.
  class ExternalSystemCall < ApiModelBase
    # indicates whether the object is active for use or not
    attr_accessor :active

    # global object uuid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
    attr_accessor :id

    # Increments every time this object is saved. Unique per object type; use it to track changes and pull only updates (delta sync).
    attr_accessor :revision

    # number of the object, like it is set in backoffice
    attr_accessor :number

    # Display name.
    attr_accessor :name

    # Display url. If this field is the the URL will be displayed to the cashier.
    attr_accessor :display_url

    # If this is enabled the request json will be sent via POST to the display URL. Otherwise the request json will be injected via Javascript.
    attr_accessor :display_url_post

    # A system URL will be called in the background without displaying anything to the cashier. The request json will always be sent via POST to the system URL. The actions in the response json will be executed by the POS immediately. Please note that if both a system URL and a display URL are set in a request, only the display URL is used.
    attr_accessor :system_url

    # HTTP basic auth login.
    attr_accessor :login

    # HTTP basic auth password.
    attr_accessor :password

    # Connect timeout in milliseconds. If the connection to the external system fails after this timeout the request will be aborted.
    attr_accessor :connect_timeout_millis

    # Request timeout in milliseconds. If the request to the external system takes longer than this timeout the request will be aborted.
    attr_accessor :request_timeout_millis

    # Customer display url. If this field is set the URL will be displayed to the customer on the customer facing display
    attr_accessor :customer_display_url

    # If true, deactivated.
    attr_accessor :deactivated

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'active' => :'active',
        :'id' => :'id',
        :'revision' => :'revision',
        :'number' => :'number',
        :'name' => :'name',
        :'display_url' => :'displayUrl',
        :'display_url_post' => :'displayUrlPost',
        :'system_url' => :'systemUrl',
        :'login' => :'login',
        :'password' => :'password',
        :'connect_timeout_millis' => :'connectTimeoutMillis',
        :'request_timeout_millis' => :'requestTimeoutMillis',
        :'customer_display_url' => :'customerDisplayUrl',
        :'deactivated' => :'deactivated'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'active' => :'Boolean',
        :'id' => :'String',
        :'revision' => :'Integer',
        :'number' => :'String',
        :'name' => :'String',
        :'display_url' => :'String',
        :'display_url_post' => :'Boolean',
        :'system_url' => :'String',
        :'login' => :'String',
        :'password' => :'String',
        :'connect_timeout_millis' => :'Integer',
        :'request_timeout_millis' => :'Integer',
        :'customer_display_url' => :'String',
        :'deactivated' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::ExternalSystemCall` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::ExternalSystemCall`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'revision')
        self.revision = attributes[:'revision']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'display_url')
        self.display_url = attributes[:'display_url']
      end

      if attributes.key?(:'display_url_post')
        self.display_url_post = attributes[:'display_url_post']
      end

      if attributes.key?(:'system_url')
        self.system_url = attributes[:'system_url']
      end

      if attributes.key?(:'login')
        self.login = attributes[:'login']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      end

      if attributes.key?(:'connect_timeout_millis')
        self.connect_timeout_millis = attributes[:'connect_timeout_millis']
      end

      if attributes.key?(:'request_timeout_millis')
        self.request_timeout_millis = attributes[:'request_timeout_millis']
      end

      if attributes.key?(:'customer_display_url')
        self.customer_display_url = attributes[:'customer_display_url']
      end

      if attributes.key?(:'deactivated')
        self.deactivated = attributes[:'deactivated']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          active == o.active &&
          id == o.id &&
          revision == o.revision &&
          number == o.number &&
          name == o.name &&
          display_url == o.display_url &&
          display_url_post == o.display_url_post &&
          system_url == o.system_url &&
          login == o.login &&
          password == o.password &&
          connect_timeout_millis == o.connect_timeout_millis &&
          request_timeout_millis == o.request_timeout_millis &&
          customer_display_url == o.customer_display_url &&
          deactivated == o.deactivated
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [active, id, revision, number, name, display_url, display_url_post, system_url, login, password, connect_timeout_millis, request_timeout_millis, customer_display_url, deactivated].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
