=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  # Scannable number ranges and actions configured for this rule set.
  class NumberRange < ApiModelBase
    attr_accessor :expression

    attr_accessor :regular_expression

    attr_accessor :function

    attr_accessor :case_sensitive

    attr_accessor :external_system_call

    attr_accessor :tag

    attr_accessor :voucher_configuration

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'expression' => :'expression',
        :'regular_expression' => :'regularExpression',
        :'function' => :'function',
        :'case_sensitive' => :'caseSensitive',
        :'external_system_call' => :'externalSystemCall',
        :'tag' => :'tag',
        :'voucher_configuration' => :'voucherConfiguration'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'expression' => :'String',
        :'regular_expression' => :'String',
        :'function' => :'String',
        :'case_sensitive' => :'Boolean',
        :'external_system_call' => :'ModelReference',
        :'tag' => :'ModelReference',
        :'voucher_configuration' => :'ModelReference'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::NumberRange` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::NumberRange`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'expression')
        self.expression = attributes[:'expression']
      end

      if attributes.key?(:'regular_expression')
        self.regular_expression = attributes[:'regular_expression']
      end

      if attributes.key?(:'function')
        self.function = attributes[:'function']
      end

      if attributes.key?(:'case_sensitive')
        self.case_sensitive = attributes[:'case_sensitive']
      end

      if attributes.key?(:'external_system_call')
        self.external_system_call = attributes[:'external_system_call']
      end

      if attributes.key?(:'tag')
        self.tag = attributes[:'tag']
      end

      if attributes.key?(:'voucher_configuration')
        self.voucher_configuration = attributes[:'voucher_configuration']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      function_validator = EnumAttributeValidator.new('String', ["ADD_ACCOUNT_TRANSACTION", "ADD_SALE", "SET_RECEIPT_ORDER_NUMBER", "REDEEM_COUPON", "LOGIN_CASHIER", "OPEN_KORONA_RESOURCE_BOOKING", "SET_RECEIPT_CUSTOMER", "SET_RECEIPT_CUSTOMER_GROUP", "SET_RECEIPT_CUSTOMER_NUMBER", "LOGOUT_CASHIER", "OPEN_INVOICE", "SET_CASH_DRAWER", "ADD_SALE_SERIAL_NUMBER", "SHOW_BUTTON_LAYOUT", "OPEN_CUSTOMER_ORDER", "OPEN_DELIVERY_NOTE", "OPEN_QUOTE", "OPEN_RENTAL", "BOOK_INSTORE_EAN_PRICE_4", "BOOK_INSTORE_EAN_PRICE_5", "BOOK_INSTORE_EAN_PRICE_6", "SET_SALE_SELLER", "EXECUTE_EXTERNAL_SYSTEM_CALL", "SET_RECEIPT_CAMPAIGN_CARD_NUMBER", "BOOK_INSTORE_EAN_WEIGHT_5", "BOOK_INSTORE_EAN_WEIGHT_5_TWO_DECIMAL_PLACES", "BOOK_INSTORE_EAN_ACCOUNT_5", "BOOK_INSTORE_EAN_ACCOUNT_6", "DEBIT_VOUCHER", "HANDLE_VOUCHER", "REDEEM_EXTERNAL_COUPON", "SET_DIGITAL_RECEIPT_EMAIL", "SET_SALE_TAG"])
      return false unless function_validator.valid?(@function)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] function Object to be assigned
    def function=(function)
      validator = EnumAttributeValidator.new('String', ["ADD_ACCOUNT_TRANSACTION", "ADD_SALE", "SET_RECEIPT_ORDER_NUMBER", "REDEEM_COUPON", "LOGIN_CASHIER", "OPEN_KORONA_RESOURCE_BOOKING", "SET_RECEIPT_CUSTOMER", "SET_RECEIPT_CUSTOMER_GROUP", "SET_RECEIPT_CUSTOMER_NUMBER", "LOGOUT_CASHIER", "OPEN_INVOICE", "SET_CASH_DRAWER", "ADD_SALE_SERIAL_NUMBER", "SHOW_BUTTON_LAYOUT", "OPEN_CUSTOMER_ORDER", "OPEN_DELIVERY_NOTE", "OPEN_QUOTE", "OPEN_RENTAL", "BOOK_INSTORE_EAN_PRICE_4", "BOOK_INSTORE_EAN_PRICE_5", "BOOK_INSTORE_EAN_PRICE_6", "SET_SALE_SELLER", "EXECUTE_EXTERNAL_SYSTEM_CALL", "SET_RECEIPT_CAMPAIGN_CARD_NUMBER", "BOOK_INSTORE_EAN_WEIGHT_5", "BOOK_INSTORE_EAN_WEIGHT_5_TWO_DECIMAL_PLACES", "BOOK_INSTORE_EAN_ACCOUNT_5", "BOOK_INSTORE_EAN_ACCOUNT_6", "DEBIT_VOUCHER", "HANDLE_VOUCHER", "REDEEM_EXTERNAL_COUPON", "SET_DIGITAL_RECEIPT_EMAIL", "SET_SALE_TAG"])
      unless validator.valid?(function)
        fail ArgumentError, "invalid value for \"function\", must be one of #{validator.allowable_values}."
      end
      @function = function
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          expression == o.expression &&
          regular_expression == o.regular_expression &&
          function == o.function &&
          case_sensitive == o.case_sensitive &&
          external_system_call == o.external_system_call &&
          tag == o.tag &&
          voucher_configuration == o.voucher_configuration
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [expression, regular_expression, function, case_sensitive, external_system_call, tag, voucher_configuration].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
