=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  class PosMaxNumbers < ApiModelBase
    attr_accessor :last_receipt_number

    attr_accessor :last_z_count

    attr_accessor :last_quote_number

    attr_accessor :last_rental_number

    attr_accessor :last_customer_order_number

    attr_accessor :last_delivery_note_number

    attr_accessor :last_store_order_number

    attr_accessor :last_pos_balance_transaction_code

    attr_accessor :last_stock_adjustment_number

    attr_accessor :last_stock_receipt_number

    attr_accessor :last_inventory_receipt_number

    attr_accessor :last_manufacturing_number

    attr_accessor :last_stock_return_number

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'last_receipt_number' => :'lastReceiptNumber',
        :'last_z_count' => :'lastZCount',
        :'last_quote_number' => :'lastQuoteNumber',
        :'last_rental_number' => :'lastRentalNumber',
        :'last_customer_order_number' => :'lastCustomerOrderNumber',
        :'last_delivery_note_number' => :'lastDeliveryNoteNumber',
        :'last_store_order_number' => :'lastStoreOrderNumber',
        :'last_pos_balance_transaction_code' => :'lastPosBalanceTransactionCode',
        :'last_stock_adjustment_number' => :'lastStockAdjustmentNumber',
        :'last_stock_receipt_number' => :'lastStockReceiptNumber',
        :'last_inventory_receipt_number' => :'lastInventoryReceiptNumber',
        :'last_manufacturing_number' => :'lastManufacturingNumber',
        :'last_stock_return_number' => :'lastStockReturnNumber'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'last_receipt_number' => :'String',
        :'last_z_count' => :'Integer',
        :'last_quote_number' => :'String',
        :'last_rental_number' => :'String',
        :'last_customer_order_number' => :'String',
        :'last_delivery_note_number' => :'String',
        :'last_store_order_number' => :'String',
        :'last_pos_balance_transaction_code' => :'String',
        :'last_stock_adjustment_number' => :'String',
        :'last_stock_receipt_number' => :'String',
        :'last_inventory_receipt_number' => :'String',
        :'last_manufacturing_number' => :'String',
        :'last_stock_return_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::PosMaxNumbers` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::PosMaxNumbers`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'last_receipt_number')
        self.last_receipt_number = attributes[:'last_receipt_number']
      end

      if attributes.key?(:'last_z_count')
        self.last_z_count = attributes[:'last_z_count']
      end

      if attributes.key?(:'last_quote_number')
        self.last_quote_number = attributes[:'last_quote_number']
      end

      if attributes.key?(:'last_rental_number')
        self.last_rental_number = attributes[:'last_rental_number']
      end

      if attributes.key?(:'last_customer_order_number')
        self.last_customer_order_number = attributes[:'last_customer_order_number']
      end

      if attributes.key?(:'last_delivery_note_number')
        self.last_delivery_note_number = attributes[:'last_delivery_note_number']
      end

      if attributes.key?(:'last_store_order_number')
        self.last_store_order_number = attributes[:'last_store_order_number']
      end

      if attributes.key?(:'last_pos_balance_transaction_code')
        self.last_pos_balance_transaction_code = attributes[:'last_pos_balance_transaction_code']
      end

      if attributes.key?(:'last_stock_adjustment_number')
        self.last_stock_adjustment_number = attributes[:'last_stock_adjustment_number']
      end

      if attributes.key?(:'last_stock_receipt_number')
        self.last_stock_receipt_number = attributes[:'last_stock_receipt_number']
      end

      if attributes.key?(:'last_inventory_receipt_number')
        self.last_inventory_receipt_number = attributes[:'last_inventory_receipt_number']
      end

      if attributes.key?(:'last_manufacturing_number')
        self.last_manufacturing_number = attributes[:'last_manufacturing_number']
      end

      if attributes.key?(:'last_stock_return_number')
        self.last_stock_return_number = attributes[:'last_stock_return_number']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          last_receipt_number == o.last_receipt_number &&
          last_z_count == o.last_z_count &&
          last_quote_number == o.last_quote_number &&
          last_rental_number == o.last_rental_number &&
          last_customer_order_number == o.last_customer_order_number &&
          last_delivery_note_number == o.last_delivery_note_number &&
          last_store_order_number == o.last_store_order_number &&
          last_pos_balance_transaction_code == o.last_pos_balance_transaction_code &&
          last_stock_adjustment_number == o.last_stock_adjustment_number &&
          last_stock_receipt_number == o.last_stock_receipt_number &&
          last_inventory_receipt_number == o.last_inventory_receipt_number &&
          last_manufacturing_number == o.last_manufacturing_number &&
          last_stock_return_number == o.last_stock_return_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [last_receipt_number, last_z_count, last_quote_number, last_rental_number, last_customer_order_number, last_delivery_note_number, last_store_order_number, last_pos_balance_transaction_code, last_stock_adjustment_number, last_stock_receipt_number, last_inventory_receipt_number, last_manufacturing_number, last_stock_return_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
