=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  class ReceiptLayoutConfiguration < ApiModelBase
    # indicates whether the object is active for use or not
    attr_accessor :active

    # global object uuid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
    attr_accessor :id

    # Increments every time this object is saved. Unique per object type; use it to track changes and pull only updates (delta sync).
    attr_accessor :revision

    # number of the object, like it is set in backoffice
    attr_accessor :number

    # Display name.
    attr_accessor :name

    # If true, show product numbers.
    attr_accessor :show_product_numbers

    # If true, show receipt number barcode.
    attr_accessor :show_receipt_number_barcode

    attr_accessor :footer_logo

    # Footer logo number.
    attr_accessor :footer_logo_number

    attr_accessor :header_logo

    # Header logo number.
    attr_accessor :header_logo_number

    # Show recommended retail price threshold.
    attr_accessor :show_recommended_retail_price_threshold

    # Item grouping.
    attr_accessor :item_grouping

    # If true, show reduced receipt information.
    attr_accessor :show_reduced_receipt_information

    # If true, show reduced customer information.
    attr_accessor :show_reduced_customer_information

    # If true, show removed items.
    attr_accessor :show_removed_items

    # If true, show total discount.
    attr_accessor :show_total_discount

    # If true, show prices on delivery notes.
    attr_accessor :show_prices_on_delivery_notes

    # If true, show tax name.
    attr_accessor :show_tax_name

    # If true, deposit summary.
    attr_accessor :deposit_summary

    # If true, show article count.
    attr_accessor :show_article_count

    # Fiscal data format.
    attr_accessor :fiscal_data_format

    # use new property fiscalDataFormat, value corresponds to the following mapping false equals TEXT & true equals TEXT_AND_QR_CODE
    attr_accessor :show_optional_fiscal_data

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'active' => :'active',
        :'id' => :'id',
        :'revision' => :'revision',
        :'number' => :'number',
        :'name' => :'name',
        :'show_product_numbers' => :'showProductNumbers',
        :'show_receipt_number_barcode' => :'showReceiptNumberBarcode',
        :'footer_logo' => :'footerLogo',
        :'footer_logo_number' => :'footerLogoNumber',
        :'header_logo' => :'headerLogo',
        :'header_logo_number' => :'headerLogoNumber',
        :'show_recommended_retail_price_threshold' => :'showRecommendedRetailPriceThreshold',
        :'item_grouping' => :'itemGrouping',
        :'show_reduced_receipt_information' => :'showReducedReceiptInformation',
        :'show_reduced_customer_information' => :'showReducedCustomerInformation',
        :'show_removed_items' => :'showRemovedItems',
        :'show_total_discount' => :'showTotalDiscount',
        :'show_prices_on_delivery_notes' => :'showPricesOnDeliveryNotes',
        :'show_tax_name' => :'showTaxName',
        :'deposit_summary' => :'depositSummary',
        :'show_article_count' => :'showArticleCount',
        :'fiscal_data_format' => :'fiscalDataFormat',
        :'show_optional_fiscal_data' => :'showOptionalFiscalData'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'active' => :'Boolean',
        :'id' => :'String',
        :'revision' => :'Integer',
        :'number' => :'String',
        :'name' => :'String',
        :'show_product_numbers' => :'Boolean',
        :'show_receipt_number_barcode' => :'Boolean',
        :'footer_logo' => :'ModelReference',
        :'footer_logo_number' => :'Integer',
        :'header_logo' => :'ModelReference',
        :'header_logo_number' => :'Integer',
        :'show_recommended_retail_price_threshold' => :'Integer',
        :'item_grouping' => :'String',
        :'show_reduced_receipt_information' => :'Boolean',
        :'show_reduced_customer_information' => :'Boolean',
        :'show_removed_items' => :'Boolean',
        :'show_total_discount' => :'Boolean',
        :'show_prices_on_delivery_notes' => :'Boolean',
        :'show_tax_name' => :'Boolean',
        :'deposit_summary' => :'Boolean',
        :'show_article_count' => :'Boolean',
        :'fiscal_data_format' => :'String',
        :'show_optional_fiscal_data' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::ReceiptLayoutConfiguration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::ReceiptLayoutConfiguration`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'revision')
        self.revision = attributes[:'revision']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'show_product_numbers')
        self.show_product_numbers = attributes[:'show_product_numbers']
      end

      if attributes.key?(:'show_receipt_number_barcode')
        self.show_receipt_number_barcode = attributes[:'show_receipt_number_barcode']
      end

      if attributes.key?(:'footer_logo')
        self.footer_logo = attributes[:'footer_logo']
      end

      if attributes.key?(:'footer_logo_number')
        self.footer_logo_number = attributes[:'footer_logo_number']
      end

      if attributes.key?(:'header_logo')
        self.header_logo = attributes[:'header_logo']
      end

      if attributes.key?(:'header_logo_number')
        self.header_logo_number = attributes[:'header_logo_number']
      end

      if attributes.key?(:'show_recommended_retail_price_threshold')
        self.show_recommended_retail_price_threshold = attributes[:'show_recommended_retail_price_threshold']
      end

      if attributes.key?(:'item_grouping')
        self.item_grouping = attributes[:'item_grouping']
      end

      if attributes.key?(:'show_reduced_receipt_information')
        self.show_reduced_receipt_information = attributes[:'show_reduced_receipt_information']
      end

      if attributes.key?(:'show_reduced_customer_information')
        self.show_reduced_customer_information = attributes[:'show_reduced_customer_information']
      end

      if attributes.key?(:'show_removed_items')
        self.show_removed_items = attributes[:'show_removed_items']
      end

      if attributes.key?(:'show_total_discount')
        self.show_total_discount = attributes[:'show_total_discount']
      end

      if attributes.key?(:'show_prices_on_delivery_notes')
        self.show_prices_on_delivery_notes = attributes[:'show_prices_on_delivery_notes']
      end

      if attributes.key?(:'show_tax_name')
        self.show_tax_name = attributes[:'show_tax_name']
      end

      if attributes.key?(:'deposit_summary')
        self.deposit_summary = attributes[:'deposit_summary']
      end

      if attributes.key?(:'show_article_count')
        self.show_article_count = attributes[:'show_article_count']
      end

      if attributes.key?(:'fiscal_data_format')
        self.fiscal_data_format = attributes[:'fiscal_data_format']
      end

      if attributes.key?(:'show_optional_fiscal_data')
        self.show_optional_fiscal_data = attributes[:'show_optional_fiscal_data']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      item_grouping_validator = EnumAttributeValidator.new('String', ["ASSORTMENT", "COMMODITY_GROUP", "NONE"])
      return false unless item_grouping_validator.valid?(@item_grouping)
      fiscal_data_format_validator = EnumAttributeValidator.new('String', ["TEXT", "QR_CODE", "TEXT_AND_QR_CODE"])
      return false unless fiscal_data_format_validator.valid?(@fiscal_data_format)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] item_grouping Object to be assigned
    def item_grouping=(item_grouping)
      validator = EnumAttributeValidator.new('String', ["ASSORTMENT", "COMMODITY_GROUP", "NONE"])
      unless validator.valid?(item_grouping)
        fail ArgumentError, "invalid value for \"item_grouping\", must be one of #{validator.allowable_values}."
      end
      @item_grouping = item_grouping
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fiscal_data_format Object to be assigned
    def fiscal_data_format=(fiscal_data_format)
      validator = EnumAttributeValidator.new('String', ["TEXT", "QR_CODE", "TEXT_AND_QR_CODE"])
      unless validator.valid?(fiscal_data_format)
        fail ArgumentError, "invalid value for \"fiscal_data_format\", must be one of #{validator.allowable_values}."
      end
      @fiscal_data_format = fiscal_data_format
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          active == o.active &&
          id == o.id &&
          revision == o.revision &&
          number == o.number &&
          name == o.name &&
          show_product_numbers == o.show_product_numbers &&
          show_receipt_number_barcode == o.show_receipt_number_barcode &&
          footer_logo == o.footer_logo &&
          footer_logo_number == o.footer_logo_number &&
          header_logo == o.header_logo &&
          header_logo_number == o.header_logo_number &&
          show_recommended_retail_price_threshold == o.show_recommended_retail_price_threshold &&
          item_grouping == o.item_grouping &&
          show_reduced_receipt_information == o.show_reduced_receipt_information &&
          show_reduced_customer_information == o.show_reduced_customer_information &&
          show_removed_items == o.show_removed_items &&
          show_total_discount == o.show_total_discount &&
          show_prices_on_delivery_notes == o.show_prices_on_delivery_notes &&
          show_tax_name == o.show_tax_name &&
          deposit_summary == o.deposit_summary &&
          show_article_count == o.show_article_count &&
          fiscal_data_format == o.fiscal_data_format &&
          show_optional_fiscal_data == o.show_optional_fiscal_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [active, id, revision, number, name, show_product_numbers, show_receipt_number_barcode, footer_logo, footer_logo_number, header_logo, header_logo_number, show_recommended_retail_price_threshold, item_grouping, show_reduced_receipt_information, show_reduced_customer_information, show_removed_items, show_total_discount, show_prices_on_delivery_notes, show_tax_name, deposit_summary, show_article_count, fiscal_data_format, show_optional_fiscal_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
