=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  # Configuration settings for the self-checkout (SCO) user interface and behavior.
  class ScoConfiguration < ApiModelBase
    # indicates whether the object is active for use or not
    attr_accessor :active

    # global object uuid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
    attr_accessor :id

    # Increments every time this object is saved. Unique per object type; use it to track changes and pull only updates (delta sync).
    attr_accessor :revision

    # number of the object, like it is set in backoffice
    attr_accessor :number

    # Name of the SCO configuration.
    attr_accessor :name

    # Timeout in seconds for displaying the thank-you page.
    attr_accessor :thank_you_page_visibility_timeout

    # Timeout in seconds for displaying the digital receipt page.
    attr_accessor :digital_receipt_visibility_timeout

    # Timeout in seconds before canceling a receipt due to inactivity.
    attr_accessor :inactivity_receipt_cancelation_timeout

    # Timeout in seconds before showing an inactivity request.
    attr_accessor :inactivity_request_timeout

    # Timeout in seconds for showing hints in the SCO interface.
    attr_accessor :hint_visibility_timeout

    # If true, coupon queries are enabled in SCO.
    attr_accessor :coupon_query

    # If true, digital receipt functionality is enabled.
    attr_accessor :digital_receipt

    # Position where SCO advertisements are displayed.
    attr_accessor :ad_position

    # Size of the advertisement area in the SCO UI.
    attr_accessor :ad_size

    # URL used to load advertisement content.
    attr_accessor :ad_url

    # Predefined SCO user interface variant.
    attr_accessor :user_interface

    # URL to a custom SCO UI when custom interface mode is used.
    attr_accessor :custom_ui_url

    # Basic auth username for accessing the custom SCO UI.
    attr_accessor :custom_ui_basic_auth_user

    # Basic auth password for accessing the custom SCO UI.
    attr_accessor :custom_ui_basic_auth_password

    attr_accessor :custom_css_file

    attr_accessor :logo_image

    attr_accessor :button_layout

    # Advanced key-value settings for SCO behavior.
    attr_accessor :advanced_settings

    # Language-specific settings for the SCO interface.
    attr_accessor :language_settings

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'active' => :'active',
        :'id' => :'id',
        :'revision' => :'revision',
        :'number' => :'number',
        :'name' => :'name',
        :'thank_you_page_visibility_timeout' => :'thankYouPageVisibilityTimeout',
        :'digital_receipt_visibility_timeout' => :'digitalReceiptVisibilityTimeout',
        :'inactivity_receipt_cancelation_timeout' => :'inactivityReceiptCancelationTimeout',
        :'inactivity_request_timeout' => :'inactivityRequestTimeout',
        :'hint_visibility_timeout' => :'hintVisibilityTimeout',
        :'coupon_query' => :'couponQuery',
        :'digital_receipt' => :'digitalReceipt',
        :'ad_position' => :'adPosition',
        :'ad_size' => :'adSize',
        :'ad_url' => :'adUrl',
        :'user_interface' => :'userInterface',
        :'custom_ui_url' => :'customUiUrl',
        :'custom_ui_basic_auth_user' => :'customUiBasicAuthUser',
        :'custom_ui_basic_auth_password' => :'customUiBasicAuthPassword',
        :'custom_css_file' => :'customCssFile',
        :'logo_image' => :'logoImage',
        :'button_layout' => :'buttonLayout',
        :'advanced_settings' => :'advancedSettings',
        :'language_settings' => :'languageSettings'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'active' => :'Boolean',
        :'id' => :'String',
        :'revision' => :'Integer',
        :'number' => :'String',
        :'name' => :'String',
        :'thank_you_page_visibility_timeout' => :'Integer',
        :'digital_receipt_visibility_timeout' => :'Integer',
        :'inactivity_receipt_cancelation_timeout' => :'Integer',
        :'inactivity_request_timeout' => :'Integer',
        :'hint_visibility_timeout' => :'Integer',
        :'coupon_query' => :'Boolean',
        :'digital_receipt' => :'Boolean',
        :'ad_position' => :'String',
        :'ad_size' => :'Integer',
        :'ad_url' => :'String',
        :'user_interface' => :'String',
        :'custom_ui_url' => :'String',
        :'custom_ui_basic_auth_user' => :'String',
        :'custom_ui_basic_auth_password' => :'String',
        :'custom_css_file' => :'File',
        :'logo_image' => :'ModelReference',
        :'button_layout' => :'ModelReference',
        :'advanced_settings' => :'Hash<String, String>',
        :'language_settings' => :'Array<ScoLanguageSetting>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::ScoConfiguration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::ScoConfiguration`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'revision')
        self.revision = attributes[:'revision']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'thank_you_page_visibility_timeout')
        self.thank_you_page_visibility_timeout = attributes[:'thank_you_page_visibility_timeout']
      end

      if attributes.key?(:'digital_receipt_visibility_timeout')
        self.digital_receipt_visibility_timeout = attributes[:'digital_receipt_visibility_timeout']
      end

      if attributes.key?(:'inactivity_receipt_cancelation_timeout')
        self.inactivity_receipt_cancelation_timeout = attributes[:'inactivity_receipt_cancelation_timeout']
      end

      if attributes.key?(:'inactivity_request_timeout')
        self.inactivity_request_timeout = attributes[:'inactivity_request_timeout']
      end

      if attributes.key?(:'hint_visibility_timeout')
        self.hint_visibility_timeout = attributes[:'hint_visibility_timeout']
      end

      if attributes.key?(:'coupon_query')
        self.coupon_query = attributes[:'coupon_query']
      end

      if attributes.key?(:'digital_receipt')
        self.digital_receipt = attributes[:'digital_receipt']
      end

      if attributes.key?(:'ad_position')
        self.ad_position = attributes[:'ad_position']
      end

      if attributes.key?(:'ad_size')
        self.ad_size = attributes[:'ad_size']
      end

      if attributes.key?(:'ad_url')
        self.ad_url = attributes[:'ad_url']
      end

      if attributes.key?(:'user_interface')
        self.user_interface = attributes[:'user_interface']
      end

      if attributes.key?(:'custom_ui_url')
        self.custom_ui_url = attributes[:'custom_ui_url']
      end

      if attributes.key?(:'custom_ui_basic_auth_user')
        self.custom_ui_basic_auth_user = attributes[:'custom_ui_basic_auth_user']
      end

      if attributes.key?(:'custom_ui_basic_auth_password')
        self.custom_ui_basic_auth_password = attributes[:'custom_ui_basic_auth_password']
      end

      if attributes.key?(:'custom_css_file')
        self.custom_css_file = attributes[:'custom_css_file']
      end

      if attributes.key?(:'logo_image')
        self.logo_image = attributes[:'logo_image']
      end

      if attributes.key?(:'button_layout')
        self.button_layout = attributes[:'button_layout']
      end

      if attributes.key?(:'advanced_settings')
        if (value = attributes[:'advanced_settings']).is_a?(Hash)
          self.advanced_settings = value
        end
      end

      if attributes.key?(:'language_settings')
        if (value = attributes[:'language_settings']).is_a?(Array)
          self.language_settings = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      ad_position_validator = EnumAttributeValidator.new('String', ["TOP", "BOTTOM", "LEFT", "RIGHT"])
      return false unless ad_position_validator.valid?(@ad_position)
      user_interface_validator = EnumAttributeValidator.new('String', ["RETAIL", "TICKET", "FOOD", "KORONA_EVENT", "CUSTOM"])
      return false unless user_interface_validator.valid?(@user_interface)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ad_position Object to be assigned
    def ad_position=(ad_position)
      validator = EnumAttributeValidator.new('String', ["TOP", "BOTTOM", "LEFT", "RIGHT"])
      unless validator.valid?(ad_position)
        fail ArgumentError, "invalid value for \"ad_position\", must be one of #{validator.allowable_values}."
      end
      @ad_position = ad_position
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] user_interface Object to be assigned
    def user_interface=(user_interface)
      validator = EnumAttributeValidator.new('String', ["RETAIL", "TICKET", "FOOD", "KORONA_EVENT", "CUSTOM"])
      unless validator.valid?(user_interface)
        fail ArgumentError, "invalid value for \"user_interface\", must be one of #{validator.allowable_values}."
      end
      @user_interface = user_interface
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          active == o.active &&
          id == o.id &&
          revision == o.revision &&
          number == o.number &&
          name == o.name &&
          thank_you_page_visibility_timeout == o.thank_you_page_visibility_timeout &&
          digital_receipt_visibility_timeout == o.digital_receipt_visibility_timeout &&
          inactivity_receipt_cancelation_timeout == o.inactivity_receipt_cancelation_timeout &&
          inactivity_request_timeout == o.inactivity_request_timeout &&
          hint_visibility_timeout == o.hint_visibility_timeout &&
          coupon_query == o.coupon_query &&
          digital_receipt == o.digital_receipt &&
          ad_position == o.ad_position &&
          ad_size == o.ad_size &&
          ad_url == o.ad_url &&
          user_interface == o.user_interface &&
          custom_ui_url == o.custom_ui_url &&
          custom_ui_basic_auth_user == o.custom_ui_basic_auth_user &&
          custom_ui_basic_auth_password == o.custom_ui_basic_auth_password &&
          custom_css_file == o.custom_css_file &&
          logo_image == o.logo_image &&
          button_layout == o.button_layout &&
          advanced_settings == o.advanced_settings &&
          language_settings == o.language_settings
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [active, id, revision, number, name, thank_you_page_visibility_timeout, digital_receipt_visibility_timeout, inactivity_receipt_cancelation_timeout, inactivity_request_timeout, hint_visibility_timeout, coupon_query, digital_receipt, ad_position, ad_size, ad_url, user_interface, custom_ui_url, custom_ui_basic_auth_user, custom_ui_basic_auth_password, custom_css_file, logo_image, button_layout, advanced_settings, language_settings].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
