=begin
#KORONA Studio API v3

#Our api provides access to our cloud services

The version of the OpenAPI document: 3.10.0
Contact: support@combase.net
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module KoronaCloudClient
  # Store order is used to request goods for an organizational units. It can later be converted to stock orders or internal transfers
  class StoreOrder < ApiModelBase
    # indicates whether the object is active for use or not
    attr_accessor :active

    # global object uuid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
    attr_accessor :id

    # Increments every time this object is saved. Unique per object type; use it to track changes and pull only updates (delta sync).
    attr_accessor :revision

    # number of the object, like it is set in backoffice
    attr_accessor :number

    # Timestamp when the store order was created. yyyy-MM-dd'T'HH:mm:ssXXX
    attr_accessor :create_time

    # Timestamp when processing of the store order started. yyyy-MM-dd'T'HH:mm:ssXXX
    attr_accessor :process_time

    # Timestamp when the store order was completed. yyyy-MM-dd'T'HH:mm:ssXXX
    attr_accessor :finish_time

    # Scheduled pickup date and time for the store order. yyyy-MM-dd'T'HH:mm:ssXXX
    attr_accessor :pickup_date

    attr_accessor :point_of_sale

    attr_accessor :target_organizational_unit

    # Optional comment for the store order.
    attr_accessor :comment

    # Number of items included in the store order.
    attr_accessor :items_count

    attr_accessor :customer_order

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'active' => :'active',
        :'id' => :'id',
        :'revision' => :'revision',
        :'number' => :'number',
        :'create_time' => :'createTime',
        :'process_time' => :'processTime',
        :'finish_time' => :'finishTime',
        :'pickup_date' => :'pickupDate',
        :'point_of_sale' => :'pointOfSale',
        :'target_organizational_unit' => :'targetOrganizationalUnit',
        :'comment' => :'comment',
        :'items_count' => :'itemsCount',
        :'customer_order' => :'customerOrder'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'active' => :'Boolean',
        :'id' => :'String',
        :'revision' => :'Integer',
        :'number' => :'String',
        :'create_time' => :'Time',
        :'process_time' => :'Time',
        :'finish_time' => :'Time',
        :'pickup_date' => :'Time',
        :'point_of_sale' => :'ModelReference',
        :'target_organizational_unit' => :'ModelReference',
        :'comment' => :'String',
        :'items_count' => :'Integer',
        :'customer_order' => :'ModelReference'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KoronaCloudClient::StoreOrder` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KoronaCloudClient::StoreOrder`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'revision')
        self.revision = attributes[:'revision']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'create_time')
        self.create_time = attributes[:'create_time']
      end

      if attributes.key?(:'process_time')
        self.process_time = attributes[:'process_time']
      end

      if attributes.key?(:'finish_time')
        self.finish_time = attributes[:'finish_time']
      end

      if attributes.key?(:'pickup_date')
        self.pickup_date = attributes[:'pickup_date']
      end

      if attributes.key?(:'point_of_sale')
        self.point_of_sale = attributes[:'point_of_sale']
      end

      if attributes.key?(:'target_organizational_unit')
        self.target_organizational_unit = attributes[:'target_organizational_unit']
      end

      if attributes.key?(:'comment')
        self.comment = attributes[:'comment']
      end

      if attributes.key?(:'items_count')
        self.items_count = attributes[:'items_count']
      end

      if attributes.key?(:'customer_order')
        self.customer_order = attributes[:'customer_order']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          active == o.active &&
          id == o.id &&
          revision == o.revision &&
          number == o.number &&
          create_time == o.create_time &&
          process_time == o.process_time &&
          finish_time == o.finish_time &&
          pickup_date == o.pickup_date &&
          point_of_sale == o.point_of_sale &&
          target_organizational_unit == o.target_organizational_unit &&
          comment == o.comment &&
          items_count == o.items_count &&
          customer_order == o.customer_order
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [active, id, revision, number, create_time, process_time, finish_time, pickup_date, point_of_sale, target_organizational_unit, comment, items_count, customer_order].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
